whresponse/urls.py
"""
whresponse URL Configuration
"""
# pylint: disable=invalid-name
from django.conf.urls import include, url
from django.contrib import admin

from responses.views import ResponseListView, ResponseDetailView

admin.autodiscover()

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', ResponseListView.as_view(), name='list'),
    url(r'^(?P<pk>[0-9]+)/(?P<slug>[\d\w-]+)',
        ResponseDetailView.as_view(), name='response'),
]

responses/models.py
"""Models for responses app"""
from django.db import models


class WhitehouseAbstractModel(models.Model):
    title = models.CharField(max_length=250)
    url = models.CharField(verbose_name=u'Whitehouse URL', max_length=250)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta(object):
        abstract = True

    @property
    def official_url(self):
        return "https://petitions.whitehouse.gov{url}".format(
            url=self.url)

    def __unicode__(self):
        return self.title


class Response(WhitehouseAbstractModel):
    slug = models.SlugField(max_length=250)
    total_signatures = models.IntegerField(verbose_name=u'Total Signatures')
    response = models.TextField(verbose_name=u'Full White House Response')

    class Meta(object):
        ordering = ["-created_at", "-total_signatures"]
        verbose_name = ('Response')
        verbose_name_plural = ('Responses')



class Petition(WhitehouseAbstractModel):
    response = models.ForeignKey(Response)
    signatures = models.IntegerField()

    class Meta(object):
        ordering = ["created_at", "-signatures"]
        verbose_name = ('Petition')
        verbose_name_plural = ('Petitions')

responses/views.py
"""Views for responses app"""
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView

from responses.models import Response, Petition


class ResponseListView(ListView):
    model = Response
    template_name = "index.html"


class ResponseDetailView(DetailView):
    model = Response
    template_name = "response.html"
    context_object_name = "response"

responses/templates/index.html
{% extends "wrapper.html" %}
{% block content %}
    <h1>Whitehouse Petition Responses</h1>
    <p>There have been {{ object_list.count }} offical responses to petitions submitted to <a href="https://petitions.whitehouse.gov/">We The People</a>.<br>As official responses are not dated, responses are ordered by the time which they were first pulled from Whitehouse.gov. The crawler runs daily and was first run on March 31st, 2013.</p>
    <ul>
    {% for response in object_list %}
        <li><a href="{% url 'response' response.pk response.slug %}">{{ response.title }}</a><br>{{ response.total_signatures }} Signatures to {{ response.petitions.count }} Petition{{ response.petitions.count|pluralize }} - Added to Viewer: {{ response.created_at.date }}</li>
    {% endfor %}
    </ul>

{% endblock content %}

responses/templates/response.html
{% extends "wrapper.html" %}

{% block title %}{{ response.title }} - WhiteHouse Petition Response Viewer{% endblock title %}

{% block social %}
    <meta name="title" content="{{ response.title }}">
    <meta property="og:title" content="{{ response.title }}">
    <meta property="og:url" content="https://petitions.nickc.at{% url 'response' response.pk response.slug %}">
    <link rel="canonical" href="https://petitions.nickc.at{% url 'response' response.pk response.slug %}"/>
{% endblock social %}

{% block content %}

<h1>{{ response.title }}</h1>
<h4>In response to {{ response.total_signatures }} signatures to th{{ response.petition_set.count|pluralize:"is,ese" }} {{ response.petition_set.count }} petition{{ response.petition_set.count|pluralize }}:</h4>
<ul>
    {% for petition in response.petition_set.all %}
        <li><a href="{{ petition.official_url }}">{{ petition.title|title }}</a> -- {{ petition.signatures }} Signatures</li>
    {% endfor %}
</ul>

{{ response.response|safe }}

<p><a href="{{ response.official_url }}" class="btn">View The Full Response</a></p>

<p>Added {{ response.created_at|date:"N j, Y" }}</p>

{% endblock content %}

templates/wrapper.html
{% load static %}
<!doctype html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="minimum-scale=1.0, width=device-width" />
    <title>{% block title %}Whitehouse Petition Response Viewer{% endblock title %}</title>
    {% block social %}
    <meta name="title" content="Whitehouse Petition Response Viewer">
    <meta property="og:title" content="Whitehouse Petition Response Viewer">

    <meta name="description" content="A better UI to view responses to 'We The People' Whitehouse petitions. Built by Nick Catalano.">
    <meta property="og:description" content="A better UI to view responses to 'We The People' Whitehouse petitions. Built by Nick Catalano.">
    <meta property="og:url" content="http://petitions.nickc.at/">
    <link rel="canonical" href="http://petitions.nickc.at/"/>
    {% endblock social %}
    <meta property="og:image" content="https://whpetition.s3.amazonaws.com/socialimage.jpg">
    <link rel="image_src" href="https://whpetition.s3.amazonaws.com/socialimage.jpg">
    
    <meta name="site" content="Whitehouse Petition Response Viewer">
    <meta property="og:site_name" content="Whitehouse Petition Response Viewer" />
    <link rel="stylesheet" href="{% static "css/bootstrap.min.css" %}">
    <style type="text/css">html {
     overflow-y: -moz-scrollbars-vertical;
     overflow-y: scroll;
}
.twitter-nav {
    width: 160px;
}
.twitter-nav iframe {
    margin-top: 5px;
    
}
</style>
</head>
<body>
        <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
        <a class="brand" href="/">Whitehouse Petition Response Viewer</a>



        <ul class="nav pull-right">

          <li><a href="{% url 'list' %}">Full List of Responses</a></li>
          <li><a href="https://petitions.whitehouse.gov/">Official Petition Site</a></li>
          <li class="twitter-nav"><a href="https://twitter.com/NickCatal" class="twitter-follow-button" data-show-count="false" data-size="large">@NickCatal</a></li>
      </ul>

      </div>
    </div>
    </div>
    <div role="main" class="container" style="margin-top: 50px">
    {% block content %}
{% endblock content %}<hr>
<p><a href="https://twitter.com/NickCatal" class="twitter-follow-button" data-show-count="false" data-size="large">Follow @NickCatal</a>
<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="//platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script></p>
<p>Built by <a href="http://twitter.com/nickcatal">Nick Catalano</a>. The source code for this site is licensed under the APACHE 2.0 license and is available on <a href="https://github.com/nickcatal/petitionviewer/">Github</a> should you wish to use or contribute to it.</p></div>



<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-106548-4', 'nickc.at');
  ga('send', 'pageview');

</script>
</body>
</html>

whresponse/templates/index.html
{% extends "wrapper.html" %}
{% block content %}
    <h1>Whitehouse Petition Responses</h1>
    <p>There have been {{ object_list.count }} offical responses to petitions submitted to <a href="https://petitions.whitehouse.gov/">We The People</a>.<br>Petitions are ordered by the time which they were first pulled from Whitehouse.gov. The crawler runs daily.</p>
    <ul>
    {% for response in object_list %}
        <li><a href="{% url 'response' response.id %}{{ response.slug }}">{{ response.title }}</a><br>{{ response.total_signatures }} Signatures to {{ response.petitions.count }} Petition{{ response.petitions.count|pluralize }} - Added to Viewer: {{ response.created_at.date }}</li>
    {% endfor %}
    </ul>

{% endblock content %}